"""make image_url not nullable

Revision ID: 8f918573f64a
Revises: b582b1098169
Create Date: 2026-01-21 00:04:50.614163

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f918573f64a"
down_revision: Union[str, Sequence[str], None] = "b582b1098169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("albums", "image_url", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("tracks", "image_url", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tracks", "image_url", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("albums", "image_url", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
